import os

# Create dummy PDFs without external dependencies like reportlab if possible.
# Actually, reportlab is easier to install. Let's just create raw text files and let PyMuPDF handle PDF creation?
# No, we need to extract from PDF. PyMuPDF (fitz) can create PDFs too.
import fitz

def create_financial_pdf(filename, title, content_pages):
    doc = fitz.open()
    for page_text in content_pages:
        page = doc.new_page()
        # insert_text doesn't wrap automatically very well, but for dummy data we can just insert line by line.
        y = 50
        page.insert_text((50, y), title, fontsize=16)
        y += 30
        for line in page_text.split('\n'):
            page.insert_text((50, y), line, fontsize=10)
            y += 12
    doc.save(filename)
    doc.close()

pdf1_content = [
    """This is a financial report for Apple Inc.
Revenue has increased by 10% year over year.
Operating income is the profit realized from a business's operations.
Operating income was $100 billion.
The balance sheet discloses assets, liabilities, and shareholders' equity.
Cash flow from operating activities is interpreted as the cash generated by the company's core business.
""",
    """The company faces various risks including market competition.
Research and development expenses were $20 billion.
Net income reached a record high this quarter.
""",
    """This page intentionally left almost blank.
a a a a a
""" # this will be filtered by length or something
]

pdf2_content = [
    """Microsoft Corporation Annual Report.
Revenue increased by 15% due to cloud growth.
The balance sheet shows total assets of $300 billion.
Cash flow from operating activities was $70 billion.
Operating income reached $80 billion, reflecting strong operational efficiency.
""",
    """We have invested heavily in artificial intelligence.
We expect these investments to drive future growth.
Our liabilities stand at $150 billion.
""",
    """Es un informe financiero. Esta página está en español.
El flujo de caja es importante.
""" # Language filter should remove this page
]

out_dir = "domain_corpus/raw"
os.makedirs(out_dir, exist_ok=True)
create_financial_pdf(os.path.join(out_dir, "Apple_10K_dummy.pdf"), "Apple 10-K", pdf1_content)
create_financial_pdf(os.path.join(out_dir, "Microsoft_10K_dummy.pdf"), "Microsoft 10-K", pdf2_content)

print("Created dummy PDFs in", out_dir)
